### ISSUE TITLE
Sub Only Videos Fail to Play

### ISSUE THREAD

**Issue by starrynightpanda** [TwitchedApp/Twitched#10]
### Description
Using a Roku Express and when trying to play a video from the Geek and Sundry channel, I get this message: An error occurred while playing a video. Error Code: -1

### Steps to Reproduce
1. Go to "Followed"
2. Select channel "Geek and Sundry"
3. Select "Videos"
4. Select a video to watch
5. Error Code: -1  message pops up

...

**Expected behavior:** The selected video should start playing.

**Actual behavior:** Error message pops up. Error Code: -1

**Roku Model:** 3710X - Roku Express+

**Roku Firmware Version:** 8.0.0 build 4128-28

**Twitched Version:** not sure

**Comment by rolandoislas** [comment]
@starrynightpanda are you subscribed to that channel?

**Comment by starrynightpanda** [comment]
I am subscribed on the twitch app and twitch.com

**Comment by rolandoislas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sub-only VODs](https://trello.com/c/Ny9nLnao/31-sub-only-vods)

**Comment by rolandoislas** [comment]
The [v1.3 beta](https://my.roku.com/add/99VMX9) should fix this. It will require a log out and relink from within the app.

**Comment by starrynightpanda** [comment]
I logged out and relinked but I am still not able to watch any VODs from "geekandsundry". The app doesn't recognize my subscription to "geekandsundry".

**Comment by rolandoislas** [comment]
@starrynightpanda The [v1.3 beta](https://my.roku.com/add/99VMX9) is required: https://my.roku.com/add/99VMX9.

**Comment by starrynightpanda** [comment]
Thank you for your help and hard work on this app! I believe I am good to go :)
